spring.application.name=find-your-partner

# Actuator endpoints exposure
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

# Application metadata for actuator endpoint info
info.app.name=Find Your Partner
info.app.description=Professional matrimony platform backend

# local logging
logging.level.root=INFO
logging.level.com.find_your_partner=DEBUG

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/matrimony
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Hibernate SQL during local development
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

